import {PublicKey,Transaction,TransactionInstruction,SystemProgram,ComputeBudgetProgram} from '@solana/web3.js';
import {TOKEN_PROGRAM_ID,TOKEN_2022_PROGRAM_ID,ASSOCIATED_TOKEN_PROGRAM_ID,createAssociatedTokenAccountIdempotentInstruction,getAssociatedTokenAddressSync} from '@solana/spl-token';

const RPC='https://api.mainnet-beta.solana.com';
const PROGRAM=new PublicKey('pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA');
const GLOBAL=new PublicKey('ADyA8hdefvWN2dbGGWFotbzWxrAvLW83WG6QCVXvJKqw');
const EVENT=new PublicKey('GS4CU59F31iL7aR2Q8zVS8DRrcRnXX1yjQ66TqNVQnaR');
const POOL=new PublicKey('GExgczEhUbdNr3V7txqvGrJPu6nt5mbgHXtWFnX8CXeF');
const PAYER=new PublicKey('7VtfL8fvgNfhz17qKRMjzQEXgbdpnHHHQRh54R9jP2RJ');
const INIT=Buffer.from('8ce9215e845ac28f','hex');
async function rpc(m,p){for(let a=0;a<10;a++){const r=await fetch(RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:m,params:p})});if(r.status===429||r.status>=500){await new Promise(x=>setTimeout(x,700+a*800));continue;}const j=await r.json();if(j.error)throw new Error(`${m}: ${JSON.stringify(j.error)}`);return j.result;}throw new Error('rpc retries exhausted');}
const pk=b=>new PublicKey(b).toBase58();function i128(b,o){const lo=b.readBigUInt64LE(o),hi=b.readBigInt64LE(o+8);return hi*(1n<<64n)+lo;}
function pool(v){if(!v)return null;const b=Buffer.from(v.data[0],'base64');return {index:b.readUInt16LE(9),creator:pk(b.subarray(11,43)),baseMint:pk(b.subarray(43,75)),quoteMint:pk(b.subarray(75,107)),lpMint:pk(b.subarray(107,139)),poolBase:pk(b.subarray(139,171)),poolQuote:pk(b.subarray(171,203)),lpSupply:b.readBigUInt64LE(203).toString(),virtual:i128(b,245).toString()};}
function tok(v){if(!v)return {exists:false,amount:'0'};const b=Buffer.from(v.data[0],'base64');return {exists:true,program:v.owner,lamports:v.lamports,mint:b.length>=72?pk(b.subarray(0,32)):null,owner:b.length>=72?pk(b.subarray(32,64)):null,amount:b.length>=72?b.readBigUInt64LE(64).toString():'0'};}
function prog(owner){if(owner===TOKEN_PROGRAM_ID.toBase58())return TOKEN_PROGRAM_ID;if(owner===TOKEN_2022_PROGRAM_ID.toBase58())return TOKEN_2022_PROGRAM_ID;throw new Error('unsupported token program '+owner);}
async function info(k){return (await rpc('getAccountInfo',[k.toBase58(),{encoding:'base64',commitment:'confirmed'}])).value;}
function initIx(p,creator,qProg,va,vault){return new TransactionInstruction({programId:PROGRAM,data:INIT,keys:[{pubkey:POOL,isSigner:false,isWritable:true},{pubkey:GLOBAL,isSigner:false,isWritable:false},{pubkey:creator,isSigner:true,isWritable:true},{pubkey:new PublicKey(p.baseMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.quoteMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.poolBase),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.poolQuote),isSigner:false,isWritable:true},{pubkey:va,isSigner:false,isWritable:false},{pubkey:vault,isSigner:false,isWritable:true},{pubkey:qProg,isSigner:false,isWritable:false},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false},{pubkey:ASSOCIATED_TOKEN_PROGRAM_ID,isSigner:false,isWritable:false},{pubkey:EVENT,isSigner:false,isWritable:false},{pubkey:PROGRAM,isSigner:false,isWritable:false}]});}
async function sim(ixs,watch){const bh=(await rpc('getLatestBlockhash',[{commitment:'processed'}])).value.blockhash;const tx=new Transaction({feePayer:PAYER,recentBlockhash:bh});tx.add(ComputeBudgetProgram.setComputeUnitLimit({units:500000}),...ixs);const raw=tx.serialize({requireAllSignatures:false,verifySignatures:false}).toString('base64');return rpc('simulateTransaction',[raw,{encoding:'base64',sigVerify:false,replaceRecentBlockhash:true,commitment:'processed',accounts:{encoding:'base64',addresses:watch.map(k=>k.toBase58())}}]);}
function summary(r,names){const v=r?.value||{},logs=v.logs||[],acs=v.accounts||[];return {slot:r?.context?.slot??null,err:v.err??null,units:v.unitsConsumed??null,accounts:Object.fromEntries(names.map((n,i)=>[n,n==='pool'?pool(acs[i]):tok(acs[i])])),anchor:logs.filter(x=>x.includes('AnchorError')),instructions:logs.filter(x=>x.includes('Instruction:')),errors:logs.filter(x=>x.includes('failed:')||x.includes('Error')),logs};}
async function main(){
 const pv=await info(POOL),p=pool(pv);const qMint=new PublicKey(p.quoteMint),qMintV=await info(qMint),qProg=prog(qMintV.owner),creator=new PublicKey(p.creator);const creatorV=await info(creator);const payerV=await info(PAYER);
 const [va]=PublicKey.findProgramAddressSync([Buffer.from('boost_vault'),POOL.toBuffer()],PROGRAM);const vault=getAssociatedTokenAddressSync(qMint,va,true,qProg,ASSOCIATED_TOKEN_PROGRAM_ID);const preQuote=tok(await info(new PublicKey(p.poolQuote))),preVault=tok(await info(vault));
 console.log('PRE',JSON.stringify({pool:p,poolQuote:preQuote,vault:preVault,creator:{pubkey:creator.toBase58(),accountOwner:creatorV?.owner??null,lamports:creatorV?.lamports??null},payer:{owner:payerV?.owner??null,lamports:payerV?.lamports??null},va:va.toBase58(),vaultAddress:vault.toBase58()},null,2));
 const setup=[createAssociatedTokenAccountIdempotentInstruction(PAYER,vault,va,qMint,qProg,ASSOCIATED_TOKEN_PROGRAM_ID),initIx(p,creator,qProg,va,vault)];const r=await sim(setup,[POOL,new PublicKey(p.poolQuote),vault]);const s=summary(r,['pool','poolQuote','vault']);console.log('TRUE_CREATOR_REINIT',JSON.stringify(s,null,2));
 const postP=s.accounts.pool,postQ=s.accounts.poolQuote,postV=s.accounts.vault;console.log('DECISIVE',JSON.stringify({err:s.err,preVirtual:p.virtual,postVirtual:postP?.virtual??null,virtualDelta:postP?(BigInt(postP.virtual)-BigInt(p.virtual)).toString():null,preQuote:preQuote.amount,postQuote:postQ?.amount??null,quoteDelta:postQ?(BigInt(postQ.amount)-BigInt(preQuote.amount)).toString():null,preVault:preVault.amount,postVault:postV?.amount??null,vaultDelta:postV?(BigInt(postV.amount)-BigInt(preVault.amount)).toString():null,instructions:s.instructions,anchor:s.anchor},null,2));
}
main().catch(e=>{console.error(e);process.exit(1)});
