import {PublicKey,Transaction,TransactionInstruction,SystemProgram,ComputeBudgetProgram} from '@solana/web3.js';
import {TOKEN_PROGRAM_ID,TOKEN_2022_PROGRAM_ID,ASSOCIATED_TOKEN_PROGRAM_ID,createAssociatedTokenAccountIdempotentInstruction,createSyncNativeInstruction,getAssociatedTokenAddressSync} from '@solana/spl-token';
const RPC='https://api.mainnet-beta.solana.com', PROGRAM=new PublicKey('pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA'), GLOBAL=new PublicKey('ADyA8hdefvWN2dbGGWFotbzWxrAvLW83WG6QCVXvJKqw'), EVENT=new PublicKey('GS4CU59F31iL7aR2Q8zVS8DRrcRnXX1yjQ66TqNVQnaR'), POOL=new PublicKey('GseMAnNDvntR5uFePZ51yZBXzNSn7GdFPkfHwfr6d77J'), USER=new PublicKey('7VtfL8fvgNfhz17qKRMjzQEXgbdpnHHHQRh54R9jP2RJ'), WSOL=new PublicKey('So11111111111111111111111111111111111111112');
const INIT=Buffer.from('8ce9215e845ac28f','hex'), DEP=Buffer.from([242,35,198,137,82,225,242,182]), WD=Buffer.from([183,18,70,156,148,109,161,34]);
const pk=b=>new PublicKey(b).toBase58(), u64=x=>{const b=Buffer.alloc(8);b.writeBigUInt64LE(BigInt(x));return b};
function i128(b,o){return b.readBigInt64LE(o+8)*(1n<<64n)+b.readBigUInt64LE(o)}
async function rpc(m,p){for(let a=0;a<12;a++){const r=await fetch(RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:m,params:p})});if(r.status===429||r.status>=500){await new Promise(x=>setTimeout(x,350+a*250));continue}const j=await r.json();if(j.error)throw Error(JSON.stringify(j.error));return j.result}throw Error('rpc retries')}
async function info(k){return (await rpc('getAccountInfo',[k.toBase58(),{encoding:'base64',commitment:'confirmed'}])).value}
async function multi(ks){return (await rpc('getMultipleAccounts',[ks.map(k=>k.toBase58()),{encoding:'base64',commitment:'confirmed'}])).value}
function pool(v){if(!v)return null;const b=Buffer.from(v.data[0],'base64');return {creator:pk(b.subarray(11,43)),baseMint:pk(b.subarray(43,75)),quoteMint:pk(b.subarray(75,107)),lpMint:pk(b.subarray(107,139)),poolBase:pk(b.subarray(139,171)),poolQuote:pk(b.subarray(171,203)),lpSupply:b.readBigUInt64LE(203),virtual:i128(b,245)}}
function tok(v){if(!v)return null;const b=Buffer.from(v.data[0],'base64');return {amount:b.readBigUInt64LE(64),lamports:BigInt(v.lamports)}}
function prog(o){if(o===TOKEN_PROGRAM_ID.toBase58())return TOKEN_PROGRAM_ID;if(o===TOKEN_2022_PROGRAM_ID.toBase58())return TOKEN_2022_PROGRAM_ID;throw Error(o)}
function keys(p,u,ub,uq,ul){return [{pubkey:POOL,isSigner:false,isWritable:true},{pubkey:GLOBAL,isSigner:false,isWritable:false},{pubkey:u,isSigner:true,isWritable:false},{pubkey:new PublicKey(p.baseMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.quoteMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.lpMint),isSigner:false,isWritable:true},{pubkey:ub,isSigner:false,isWritable:true},{pubkey:uq,isSigner:false,isWritable:true},{pubkey:ul,isSigner:false,isWritable:true},{pubkey:new PublicKey(p.poolBase),isSigner:false,isWritable:true},{pubkey:new PublicKey(p.poolQuote),isSigner:false,isWritable:true},{pubkey:TOKEN_PROGRAM_ID,isSigner:false,isWritable:false},{pubkey:TOKEN_2022_PROGRAM_ID,isSigner:false,isWritable:false},{pubkey:EVENT,isSigner:false,isWritable:false},{pubkey:PROGRAM,isSigner:false,isWritable:false}]}
function dep(p,ub,uq,ul,lp){return new TransactionInstruction({programId:PROGRAM,data:Buffer.concat([DEP,u64(lp),u64(10_000_000),u64(1_000_000)]),keys:keys(p,USER,ub,uq,ul)})}
function wd(p,ub,uq,ul,lp){return new TransactionInstruction({programId:PROGRAM,data:Buffer.concat([WD,u64(lp),u64(0),u64(0)]),keys:keys(p,USER,ub,uq,ul)})}
function init(p,qprog,va,vault){return new TransactionInstruction({programId:PROGRAM,data:INIT,keys:[{pubkey:POOL,isSigner:false,isWritable:true},{pubkey:GLOBAL,isSigner:false,isWritable:false},{pubkey:new PublicKey(p.creator),isSigner:true,isWritable:true},{pubkey:new PublicKey(p.baseMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.quoteMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.poolBase),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.poolQuote),isSigner:false,isWritable:true},{pubkey:va,isSigner:false,isWritable:false},{pubkey:vault,isSigner:false,isWritable:true},{pubkey:qprog,isSigner:false,isWritable:false},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false},{pubkey:ASSOCIATED_TOKEN_PROGRAM_ID,isSigner:false,isWritable:false},{pubkey:EVENT,isSigner:false,isWritable:false},{pubkey:PROGRAM,isSigner:false,isWritable:false}]})}
function raw(ixs,bh){const t=new Transaction({feePayer:USER,recentBlockhash:bh});t.add(ComputeBudgetProgram.setComputeUnitLimit({units:1_000_000}),...ixs);return t.serialize({requireAllSignatures:false,verifySignatures:false}).toString('base64')}
async function pair(a,b,watch,bh){const cfg={encoding:'base64',sigVerify:false,replaceRecentBlockhash:false,commitment:'processed',accounts:{encoding:'base64',addresses:watch.map(x=>x.toBase58())}};for(let n=0;n<8;n++){const body=[{jsonrpc:'2.0',id:1,method:'simulateTransaction',params:[raw(a,bh),cfg]},{jsonrpc:'2.0',id:2,method:'simulateTransaction',params:[raw(b,bh),cfg]}];const r=await fetch(RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(r.status===429){await new Promise(x=>setTimeout(x,500+n*300));continue}const z=await r.json(),x=z.find(q=>q.id===1)?.result,y=z.find(q=>q.id===2)?.result;if(x?.context?.slot===y?.context?.slot)return [x,y]}throw Error('no same slot')}
function state(r){const a=r.value.accounts||[],p=pool(a[0]),ub=tok(a[1]),uq=tok(a[2]),ul=tok(a[3]),pb=tok(a[4]),pq=tok(a[5]),v=tok(a[6]);return {slot:r.context.slot,err:r.value.err,virtual:p?.virtual??null,userBase:ub?.amount??null,userQuote:uq?.amount??null,userLp:ul?.amount??null,poolBase:pb?.amount??null,poolQuote:pq?.amount??null,vault:v?.amount??null,units:r.value.unitsConsumed,logs:r.value.logs||[]}}
async function main(){const p=pool(await info(POOL));if(p.virtual!==0n)throw Error('live virtual nonzero');const [bm,qm,lm]=await multi([new PublicKey(p.baseMint),new PublicKey(p.quoteMint),new PublicKey(p.lpMint)]),bp=prog(bm.owner),qp=prog(qm.owner),lp=prog(lm.owner);const ub=getAssociatedTokenAddressSync(new PublicKey(p.baseMint),USER,true,bp,ASSOCIATED_TOKEN_PROGRAM_ID),uq=getAssociatedTokenAddressSync(WSOL,USER,true,qp,ASSOCIATED_TOKEN_PROGRAM_ID),ul=getAssociatedTokenAddressSync(new PublicKey(p.lpMint),USER,true,lp,ASSOCIATED_TOKEN_PROGRAM_ID);const [va]=PublicKey.findProgramAddressSync([Buffer.from('boost_vault'),POOL.toBuffer()],PROGRAM),vault=getAssociatedTokenAddressSync(WSOL,va,true,qp,ASSOCIATED_TOKEN_PROGRAM_ID);const setup=[createAssociatedTokenAccountIdempotentInstruction(USER,vault,va,WSOL,qp,ASSOCIATED_TOKEN_PROGRAM_ID),init(p,qp,va,vault),createAssociatedTokenAccountIdempotentInstruction(USER,uq,USER,WSOL,qp,ASSOCIATED_TOKEN_PROGRAM_ID),createAssociatedTokenAccountIdempotentInstruction(USER,ul,USER,new PublicKey(p.lpMint),lp,ASSOCIATED_TOKEN_PROGRAM_ID),SystemProgram.transfer({fromPubkey:USER,toPubkey:uq,lamports:2_000_000}),createSyncNativeInstruction(uq,qp)];const watch=[POOL,ub,uq,ul,new PublicKey(p.poolBase),new PublicKey(p.poolQuote),vault],bh=(await rpc('getLatestBlockhash',[{commitment:'processed'}])).value.blockhash;for(const amt of [1n,2n,10n,100n,1000n,10000n,100000n]){for(const cycles of [1,2,3]){const ops=[];for(let i=0;i<cycles;i++)ops.push(dep(p,ub,uq,ul,amt),wd(p,ub,uq,ul,amt));let c,t;try{[c,t]=await pair(setup,[...setup,...ops],watch,bh)}catch(e){console.log('CASE_SERIALIZE_OR_RPC',JSON.stringify({amt:amt.toString(),cycles,error:String(e)}));continue}const C=state(c),T=state(t),d=(x,y)=>x===null||y===null?null:(y-x).toString();console.log('CASE',JSON.stringify({amt:amt.toString(),cycles,slot:C.slot,controlErr:C.err,testErr:T.err,dVirtual:d(C.virtual,T.virtual),dUserBase:d(C.userBase,T.userBase),dUserQuote:d(C.userQuote,T.userQuote),dPoolBase:d(C.poolBase,T.poolBase),dPoolQuote:d(C.poolQuote,T.poolQuote),dVault:d(C.vault,T.vault),endLp:T.userLp?.toString(),units:T.units,anchor:T.logs.filter(x=>x.includes('AnchorError')||x.includes('Error Code:'))},null,2))}}}
main().catch(e=>{console.error(e);process.exit(1)});
