import {PublicKey,Transaction,TransactionInstruction,SystemProgram,ComputeBudgetProgram} from '@solana/web3.js';
import {TOKEN_PROGRAM_ID,TOKEN_2022_PROGRAM_ID,ASSOCIATED_TOKEN_PROGRAM_ID,createAssociatedTokenAccountIdempotentInstruction,createSyncNativeInstruction,getAssociatedTokenAddressSync} from '@solana/spl-token';

const RPC='https://api.mainnet-beta.solana.com';
const PROGRAM=new PublicKey('pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA');
const GLOBAL=new PublicKey('ADyA8hdefvWN2dbGGWFotbzWxrAvLW83WG6QCVXvJKqw');
const EVENT=new PublicKey('GS4CU59F31iL7aR2Q8zVS8DRrcRnXX1yjQ66TqNVQnaR');
const POOL=new PublicKey('GseMAnNDvntR5uFePZ51yZBXzNSn7GdFPkfHwfr6d77J');
const USER=new PublicKey('7VtfL8fvgNfhz17qKRMjzQEXgbdpnHHHQRh54R9jP2RJ');
const USER_BASE=new PublicKey('8p3NAXLRSaBdrYZspZ5Eq9RCKcTFq8LGfcqcncthg4gn');
const WSOL=new PublicKey('So11111111111111111111111111111111111111112');
const INIT=Buffer.from('8ce9215e845ac28f','hex');
const DEPOSIT=Buffer.from([242,35,198,137,82,225,242,182]);

async function rpc(method,params){for(let a=0;a<9;a++){const r=await fetch(RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});if(r.status===429||r.status>=500){await new Promise(x=>setTimeout(x,650+a*750));continue;}const j=await r.json();if(j.error)throw new Error(`${method}: ${JSON.stringify(j.error)}`);return j.result;}throw new Error(`${method}: retries exhausted`);}
const pk=b=>new PublicKey(b).toBase58();
function i128(b,o){const lo=b.readBigUInt64LE(o),hi=b.readBigInt64LE(o+8);return hi*(1n<<64n)+lo;}
function pool(v){if(!v)return null;const b=Buffer.from(v.data[0],'base64');return {creator:pk(b.subarray(11,43)),baseMint:pk(b.subarray(43,75)),quoteMint:pk(b.subarray(75,107)),lpMint:pk(b.subarray(107,139)),poolBase:pk(b.subarray(139,171)),poolQuote:pk(b.subarray(171,203)),lpSupply:b.readBigUInt64LE(203).toString(),virtual:i128(b,245).toString()};}
function tok(v){if(!v)return {exists:false,amount:'0'};const b=Buffer.from(v.data[0],'base64');return {exists:true,program:v.owner,lamports:v.lamports,mint:b.length>=72?pk(b.subarray(0,32)):null,owner:b.length>=72?pk(b.subarray(32,64)):null,amount:b.length>=72?b.readBigUInt64LE(64).toString():'0'};}
function prog(owner){if(owner===TOKEN_PROGRAM_ID.toBase58())return TOKEN_PROGRAM_ID;if(owner===TOKEN_2022_PROGRAM_ID.toBase58())return TOKEN_2022_PROGRAM_ID;throw new Error('unsupported mint program '+owner);}
async function info(k){return (await rpc('getAccountInfo',[k.toBase58(),{encoding:'base64',commitment:'confirmed'}])).value;}
async function multi(keys){return (await rpc('getMultipleAccounts',[keys.map(k=>k.toBase58()),{encoding:'base64',commitment:'confirmed'}])).value;}
function u64(x){const b=Buffer.alloc(8);b.writeBigUInt64LE(BigInt(x));return b;}
function ceil(a,b){return (a+b-1n)/b;}
function initIx(p,creator,qProg,va,vault){return new TransactionInstruction({programId:PROGRAM,data:INIT,keys:[{pubkey:POOL,isSigner:false,isWritable:true},{pubkey:GLOBAL,isSigner:false,isWritable:false},{pubkey:creator,isSigner:true,isWritable:true},{pubkey:new PublicKey(p.baseMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.quoteMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.poolBase),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.poolQuote),isSigner:false,isWritable:true},{pubkey:va,isSigner:false,isWritable:false},{pubkey:vault,isSigner:false,isWritable:true},{pubkey:qProg,isSigner:false,isWritable:false},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false},{pubkey:ASSOCIATED_TOKEN_PROGRAM_ID,isSigner:false,isWritable:false},{pubkey:EVENT,isSigner:false,isWritable:false},{pubkey:PROGRAM,isSigner:false,isWritable:false}]});}
function liquidityKeys(p,user,userBase,userQuote,userLp){return [{pubkey:POOL,isSigner:false,isWritable:true},{pubkey:GLOBAL,isSigner:false,isWritable:false},{pubkey:user,isSigner:true,isWritable:false},{pubkey:new PublicKey(p.baseMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.quoteMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.lpMint),isSigner:false,isWritable:true},{pubkey:userBase,isSigner:false,isWritable:true},{pubkey:userQuote,isSigner:false,isWritable:true},{pubkey:userLp,isSigner:false,isWritable:true},{pubkey:new PublicKey(p.poolBase),isSigner:false,isWritable:true},{pubkey:new PublicKey(p.poolQuote),isSigner:false,isWritable:true},{pubkey:TOKEN_PROGRAM_ID,isSigner:false,isWritable:false},{pubkey:TOKEN_2022_PROGRAM_ID,isSigner:false,isWritable:false},{pubkey:EVENT,isSigner:false,isWritable:false},{pubkey:PROGRAM,isSigner:false,isWritable:false}];}
function depositIx(p,user,userBase,userQuote,userLp,lp,maxBase,maxQuote){return new TransactionInstruction({programId:PROGRAM,data:Buffer.concat([DEPOSIT,u64(lp),u64(maxBase),u64(maxQuote)]),keys:liquidityKeys(p,user,userBase,userQuote,userLp)});}
async function sim(ixs,watch){const bh=(await rpc('getLatestBlockhash',[{commitment:'processed'}])).value.blockhash;const tx=new Transaction({feePayer:USER,recentBlockhash:bh});tx.add(ComputeBudgetProgram.setComputeUnitLimit({units:700000}),...ixs);const raw=tx.serialize({requireAllSignatures:false,verifySignatures:false}).toString('base64');return rpc('simulateTransaction',[raw,{encoding:'base64',sigVerify:false,replaceRecentBlockhash:true,commitment:'processed',accounts:{encoding:'base64',addresses:watch.map(k=>k.toBase58())}}]);}
function summarize(r,names){const v=r?.value||{},logs=v.logs||[],acs=v.accounts||[];return {err:v.err??null,units:v.unitsConsumed??null,instructions:logs.filter(x=>x.includes('Instruction:')),anchor:logs.filter(x=>x.includes('AnchorError')),errors:logs.filter(x=>x.includes('failed:')||x.includes('Error')),accounts:Object.fromEntries(names.map((n,i)=>[n,n==='pool'?pool(acs[i]):tok(acs[i])])),logs};}
async function main(){
 const p=pool(await info(POOL));if(!p||BigInt(p.virtual)!==0n||p.quoteMint!==WSOL.toBase58())throw new Error('control pool not in expected pre-BOOST state');
 const [baseMintV,quoteMintV,lpMintV,userBaseV,userV]=await multi([new PublicKey(p.baseMint),new PublicKey(p.quoteMint),new PublicKey(p.lpMint),USER_BASE,USER]);
 const bProg=prog(baseMintV.owner),qProg=prog(quoteMintV.owner),lpProg=prog(lpMintV.owner);const ub=tok(userBaseV);if(!ub.exists||ub.owner!==USER.toBase58()||ub.mint!==p.baseMint||BigInt(ub.amount)<1000n)throw new Error('hardcoded live base holder changed');if(!userV||userV.owner!==SystemProgram.programId.toBase58()||userV.lamports<30_000_000)throw new Error('hardcoded wallet no longer suitable');
 const creator=new PublicKey(p.creator),[va]=PublicKey.findProgramAddressSync([Buffer.from('boost_vault'),POOL.toBuffer()],PROGRAM),vault=getAssociatedTokenAddressSync(WSOL,va,true,qProg,ASSOCIATED_TOKEN_PROGRAM_ID);const userQuote=getAssociatedTokenAddressSync(WSOL,USER,true,qProg,ASSOCIATED_TOKEN_PROGRAM_ID),userLp=getAssociatedTokenAddressSync(new PublicKey(p.lpMint),USER,true,lpProg,ASSOCIATED_TOKEN_PROGRAM_ID);
 const precreate=createAssociatedTokenAccountIdempotentInstruction(USER,vault,va,WSOL,qProg,ASSOCIATED_TOKEN_PROGRAM_ID),init=initIx(p,creator,qProg,va,vault);
 const initR=await sim([precreate,init],[POOL,new PublicKey(p.poolBase),new PublicKey(p.poolQuote),vault]);const initS=summarize(initR,['pool','poolBase','poolQuote','vault']);console.log('INIT',JSON.stringify(initS,null,2));if(initS.err!==null)throw new Error('true init simulation failed');
 const pp=initS.accounts.pool,B=BigInt(initS.accounts.poolBase.amount),Q=BigInt(initS.accounts.poolQuote.amount),S=BigInt(pp.lpSupply),V=BigInt(initS.accounts.vault.amount);if(BigInt(pp.virtual)<=0n||V<=0n)throw new Error('init did not establish BOOST state');
 let lp=(BigInt(ub.amount)*S)/(B*100n);if(lp<1000n)lp=1000n;const baseIn=ceil(B*lp,S),quoteIn=ceil(Q*lp,S);if(baseIn>BigInt(ub.amount)/10n)throw new Error('base requirement unexpectedly high');const maxBase=baseIn+ceil(baseIn,100n)+10n,maxQuote=quoteIn+ceil(quoteIn,100n)+10n,wrap=maxQuote+2500000n;
 const setup=[precreate,init,createAssociatedTokenAccountIdempotentInstruction(USER,userQuote,USER,WSOL,qProg,ASSOCIATED_TOKEN_PROGRAM_ID),createAssociatedTokenAccountIdempotentInstruction(USER,userLp,USER,new PublicKey(p.lpMint),lpProg,ASSOCIATED_TOKEN_PROGRAM_ID),SystemProgram.transfer({fromPubkey:USER,toPubkey:userQuote,lamports:Number(wrap)}),createSyncNativeInstruction(userQuote,qProg),depositIx(p,USER,USER_BASE,userQuote,userLp,lp,maxBase,maxQuote)];
 const r=await sim(setup,[POOL,USER_BASE,userQuote,userLp,new PublicKey(p.poolBase),new PublicKey(p.poolQuote),vault]);const s=summarize(r,['pool','userBase','userQuote','userLp','poolBase','poolQuote','vault']);console.log('BOOSTED_DEPOSIT',JSON.stringify({plan:{lp:lp.toString(),baseIn:baseIn.toString(),quoteIn:quoteIn.toString(),virtual:pp.virtual,vault:V.toString()},result:s},null,2));console.log('DECISIVE',JSON.stringify({depositAccepted:s.err===null&&s.instructions.some(x=>x.includes('Deposit')),err:s.err,anchor:s.anchor,postLp:s.accounts.userLp?.amount??null,postVirtual:s.accounts.pool?.virtual??null},null,2));
}
main().catch(e=>{console.error(e);process.exit(1)});
