import fs from 'node:fs';
import bs58 from 'bs58';
import {PublicKey,Transaction,TransactionInstruction,SystemProgram,ComputeBudgetProgram} from '@solana/web3.js';
import {TOKEN_PROGRAM_ID,TOKEN_2022_PROGRAM_ID,ASSOCIATED_TOKEN_PROGRAM_ID,createAssociatedTokenAccountIdempotentInstruction,getAssociatedTokenAddressSync} from '@solana/spl-token';
const RPC='https://api.mainnet-beta.solana.com';
const PROGRAM=new PublicKey('pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA'),GLOBAL=new PublicKey('ADyA8hdefvWN2dbGGWFotbzWxrAvLW83WG6QCVXvJKqw'),EVENT=new PublicKey('GS4CU59F31iL7aR2Q8zVS8DRrcRnXX1yjQ66TqNVQnaR'),WSOL=new PublicKey('So11111111111111111111111111111111111111112'),PAYER=new PublicKey('7VtfL8fvgNfhz17qKRMjzQEXgbdpnHHHQRh54R9jP2RJ');
const INIT=Buffer.from('8ce9215e845ac28f','hex'),idl=JSON.parse(fs.readFileSync('idl/pump_amm.json','utf8')),POOL_DISC=Buffer.from(idl.accounts.find(x=>String(x.name).toLowerCase()==='pool').discriminator);
async function rpc(m,p){for(let a=0;a<10;a++){const r=await fetch(RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:m,params:p})});if(r.status===429||r.status>=500){await new Promise(x=>setTimeout(x,650+a*750));continue;}const j=await r.json();if(j.error)throw new Error(`${m}: ${JSON.stringify(j.error)}`);return j.result;}throw new Error('rpc exhausted');}
const pk=b=>new PublicKey(b).toBase58();function i128(b,o){const lo=b.readBigUInt64LE(o),hi=b.readBigInt64LE(o+8);return hi*(1n<<64n)+lo;}
function pool(k,v){const b=Buffer.from(v.data[0],'base64');return {pubkey:k,index:b.readUInt16LE(9),creator:pk(b.subarray(11,43)),baseMint:pk(b.subarray(43,75)),quoteMint:pk(b.subarray(75,107)),lpMint:pk(b.subarray(107,139)),poolBase:pk(b.subarray(139,171)),poolQuote:pk(b.subarray(171,203)),lpSupply:b.readBigUInt64LE(203).toString(),virtual:i128(b,245).toString()};}
function token(v){if(!v)return {exists:false,amount:'0'};const b=Buffer.from(v.data[0],'base64');return {exists:true,program:v.owner,amount:b.length>=72?b.readBigUInt64LE(64).toString():'0'};}
function mint(v){if(!v)return null;const b=Buffer.from(v.data[0],'base64');return {program:v.owner,len:b.length,supply:b.length>=44?b.readBigUInt64LE(36).toString():'0',decimals:b.length>=45?b[44]:null,mintAuthorityOption:b.length>=4?b.readUInt32LE(0):null};}
function prog(owner){if(owner===TOKEN_PROGRAM_ID.toBase58())return TOKEN_PROGRAM_ID;if(owner===TOKEN_2022_PROGRAM_ID.toBase58())return TOKEN_2022_PROGRAM_ID;throw new Error('unsupported '+owner);}
async function multi(keys){const out=[];for(let i=0;i<keys.length;i+=100){const r=await rpc('getMultipleAccounts',[keys.slice(i,i+100).map(k=>k.toBase58()),{encoding:'base64',commitment:'confirmed'}]);out.push(...r.value);if(i+100<keys.length)await new Promise(x=>setTimeout(x,100));}return out;}
async function info(k){return (await rpc('getAccountInfo',[k.toBase58(),{encoding:'base64',commitment:'confirmed'}])).value;}
function ix(p,k,c,qp,va,vault){return new TransactionInstruction({programId:PROGRAM,data:INIT,keys:[{pubkey:k,isSigner:false,isWritable:true},{pubkey:GLOBAL,isSigner:false,isWritable:false},{pubkey:c,isSigner:true,isWritable:true},{pubkey:new PublicKey(p.baseMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.quoteMint),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.poolBase),isSigner:false,isWritable:false},{pubkey:new PublicKey(p.poolQuote),isSigner:false,isWritable:true},{pubkey:va,isSigner:false,isWritable:false},{pubkey:vault,isSigner:false,isWritable:true},{pubkey:qp,isSigner:false,isWritable:false},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false},{pubkey:ASSOCIATED_TOKEN_PROGRAM_ID,isSigner:false,isWritable:false},{pubkey:EVENT,isSigner:false,isWritable:false},{pubkey:PROGRAM,isSigner:false,isWritable:false}]});}
async function sim(p,k,c,qp,va,vault){const setup=[createAssociatedTokenAccountIdempotentInstruction(PAYER,vault,va,new PublicKey(p.quoteMint),qp,ASSOCIATED_TOKEN_PROGRAM_ID),ix(p,k,c,qp,va,vault)],bh=(await rpc('getLatestBlockhash',[{commitment:'processed'}])).value.blockhash,tx=new Transaction({feePayer:PAYER,recentBlockhash:bh});tx.add(ComputeBudgetProgram.setComputeUnitLimit({units:400000}),...setup);const raw=tx.serialize({requireAllSignatures:false,verifySignatures:false}).toString('base64');return rpc('simulateTransaction',[raw,{encoding:'base64',sigVerify:false,replaceRecentBlockhash:true,commitment:'processed',accounts:{encoding:'base64',addresses:[k.toBase58(),p.poolQuote,vault.toBase58()]}}]);}
function logs(r){const v=r?.value||{},ls=v.logs||[],txt=ls.join('\n');return {err:v.err??null,sawInit:txt.includes('Instruction: InitBoost'),anchor:ls.filter(x=>x.includes('AnchorError')),errors:ls.filter(x=>x.includes('failed:')||x.includes('Error')),logs:ls};}
async function main(){const idx=Buffer.alloc(2);idx.writeUInt16LE(0);const rows=await rpc('getProgramAccounts',[PROGRAM.toBase58(),{encoding:'base64',commitment:'confirmed',filters:[{dataSize:300},{memcmp:{offset:0,bytes:bs58.encode(POOL_DISC)}},{memcmp:{offset:9,bytes:bs58.encode(idx)}},{memcmp:{offset:75,bytes:bs58.encode(WSOL.toBuffer())}}]}]);console.log('INDEX0_WSOL_ROWS',rows.length);const ps=rows.map(x=>pool(x.pubkey,x.account)).filter(x=>BigInt(x.virtual)===0n);console.log('INDEX0_WSOL_V0',ps.length);
 const vals=await multi(ps.flatMap(p=>[new PublicKey(p.lpMint),new PublicKey(p.poolQuote)]));const candidates=[];for(let i=0;i<ps.length;i++){const lm=mint(vals[2*i]),q=token(vals[2*i+1]);if(!lm||!q.exists)continue;const circ=BigInt(lm.supply),qa=BigInt(q.amount);if(circ>0n&&qa>1_000_000n)candidates.push({...ps[i],lpMintState:lm,circulating:circ,quoteAmount:qa});}candidates.sort((a,b)=>a.quoteAmount===b.quoteAmount?0:(a.quoteAmount>b.quoteAmount?-1:1));console.log('CIRCULATING_INDEX0_COUNT',candidates.length);console.log('TOP',JSON.stringify(candidates.slice(0,20).map(x=>({pool:x.pubkey,creator:x.creator,lpSupplyState:x.lpSupply,circulating:x.circulating.toString(),quote:x.quoteAmount.toString()})),null,2));let tested=0;
 for(const p of candidates.slice(0,30)){const k=new PublicKey(p.pubkey),c=new PublicKey(p.creator),qm=await info(new PublicKey(p.quoteMint));let qp;try{qp=prog(qm.owner);}catch{continue;}const [va]=PublicKey.findProgramAddressSync([Buffer.from('boost_vault'),k.toBuffer()],PROGRAM),vault=getAssociatedTokenAddressSync(new PublicKey(p.quoteMint),va,true,qp,ASSOCIATED_TOKEN_PROGRAM_ID),preV=token(await info(vault)),creatorV=await info(c);let r;try{r=await sim(p,k,c,qp,va,vault);}catch(e){console.log('SIM_RPC_ERROR',p.pubkey,String(e));continue;}const s=logs(r),acs=r?.value?.accounts||[],pp=acs[0]?pool(p.pubkey,acs[0]):null,pq=token(acs[1]),pv=token(acs[2]),out={pool:p.pubkey,creator:p.creator,creatorAccountOwner:creatorV?.owner??null,circulatingLp:p.circulating.toString(),poolLpSupply:p.lpSupply,preQuote:p.quoteAmount.toString(),preVirtual:p.virtual,preVault:preV.amount,err:s.err,anchor:s.anchor,postVirtual:pp?.virtual??null,postQuote:pq.amount,postVault:pv.amount,quoteDelta:acs[1]?(BigInt(pq.amount)-p.quoteAmount).toString():null,vaultDelta:acs[2]?(BigInt(pv.amount)-BigInt(preV.amount)).toString():null};console.log('INDEX0_CIRC_RESULT',JSON.stringify(out,null,2));tested++;if(s.err===null&&pp&&BigInt(pp.virtual)>0n){console.log('DECISIVE_INDEX0_USER_POOL_BOOST_ACCEPTED',JSON.stringify(out,null,2));return;}if(tested>=15)break;}
 console.log('FINAL_NO_FULL_INIT',JSON.stringify({tested,candidates:candidates.length}));}
main().catch(e=>{console.error(e);process.exit(1)});
