import BN from 'bn.js';
import {Connection,PublicKey,Transaction,TransactionInstruction,ComputeBudgetProgram,SystemProgram} from '@solana/web3.js';
import {getAssociatedTokenAddressSync} from '@solana/spl-token';
import {OnlinePumpAmmSdk,PUMP_AMM_SDK} from '@pump-fun/pump-swap-sdk';
const RPC='https://api.mainnet-beta.solana.com';
const PROGRAM=new PublicKey('pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA');
const USER=new PublicKey('7VtfL8fvgNfhz17qKRMjzQEXgbdpnHHHQRh54R9jP2RJ');
const POOL=new PublicKey('GseMAnNDvntR5uFePZ51yZBXzNSn7GdFPkfHwfr6d77J');
const FOREIGN_BASE=new PublicKey('DnKkDNX1ShRRDDfKj8GtzigLDJFkZ9rugYP4W3V2P3h6');
const pv2=m=>PublicKey.findProgramAddressSync([Buffer.from('pool-v2'),m.toBuffer()],PROGRAM)[0];
const c=new Connection(RPC,'confirmed');
async function rpc(method,params){for(let a=0;a<14;a++){const r=await fetch(RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});if(r.status===429||r.status>=500){await new Promise(x=>setTimeout(x,300+a*250));continue}const j=await r.json();if(j.error)throw Error(JSON.stringify(j.error));return j.result}throw Error('rpc retries')}
function clone(ix,keys=ix.keys){return new TransactionInstruction({programId:ix.programId,data:Buffer.from(ix.data),keys:keys.map(k=>({...k}))})}
function raw(ix,bh){const t=new Transaction({feePayer:USER,recentBlockhash:bh});t.add(ComputeBudgetProgram.setComputeUnitLimit({units:500000}),ix);return t.serialize({requireAllSignatures:false,verifySignatures:false}).toString('base64')}
function tokenAmount(a){if(!a)return null;const b=Buffer.from(a.data[0],'base64');return b.length>=72?b.readBigUInt64LE(64).toString():null}
function summarize(x,watchNames){const v=x?.result?.value||x?.value||{},logs=v.logs||[],acs=v.accounts||[];return {slot:(x?.result?.context?.slot??x?.context?.slot??null),err:v.err??null,units:v.unitsConsumed??null,accounts:Object.fromEntries(watchNames.map((n,i)=>[n,tokenAmount(acs[i])])),anchor:logs.filter(l=>l.includes('AnchorError')||l.includes('Error Code:')),failed:logs.filter(l=>l.includes('failed:')),instructions:logs.filter(l=>l.includes('Instruction:')),returns:logs.filter(l=>l.includes('Program return:'))}}
async function main(){const sdk=new OnlinePumpAmmSdk(c),state=await sdk.swapSolanaState(POOL,USER);const correctPv2=pv2(state.pool.baseMint),foreignPv2=pv2(FOREIGN_BASE);console.log('CONFIG',JSON.stringify({coinCreator:state.pool.coinCreator.toBase58(),isCashbackCoin:state.pool.isCashbackCoin,buybackBasisPoints:state.globalConfig?.buybackBasisPoints?.toString?.()??null,buybackFeeRecipients:(state.globalConfig?.buybackFeeRecipients??[]).map(x=>x.toBase58()),quoteTokenProgram:state.quoteTokenProgram?.toBase58?.()??null},null,2));
 const ixs=await PUMP_AMM_SDK.buyQuoteInput(state,new BN(1_000_000),5);const buy=ixs.find(ix=>ix.programId.equals(PROGRAM));if(!buy)throw Error('buy ix missing');const K=buy.keys;const pv2i=K.findIndex(k=>k.pubkey.equals(correctPv2));if(pv2i<0)throw Error('poolv2 missing');const recipientSet=new Set((state.globalConfig?.buybackFeeRecipients??[]).map(x=>x.toBase58()));const ri=K.findIndex((k,i)=>i>pv2i&&recipientSet.has(k.pubkey.toBase58()));if(ri<0||ri+1>=K.length)throw Error('buyback pair missing');const ai=ri+1;const buybackRecip=K[ri].pubkey,buybackAta=K[ai].pubkey;console.log('BUY_META',JSON.stringify({keyCount:K.length,data:buy.data.toString('hex'),pv2i,ri,ai,correctPv2:correctPv2.toBase58(),buybackRecip:buybackRecip.toBase58(),buybackAta:buybackAta.toBase58(),keys:K.map((k,i)=>({i,p:k.pubkey.toBase58(),w:k.isWritable,s:k.isSigner}))},null,2));
 const cases={control:clone(buy),foreign_poolv2:clone(buy,K.map((k,i)=>i===pv2i?{...k,pubkey:foreignPv2}:k)),system_as_poolv2:clone(buy,K.map((k,i)=>i===pv2i?{...k,pubkey:SystemProgram.programId}:k)),omit_poolv2:clone(buy,K.filter((_,i)=>i!==pv2i)),swap_poolv2_buyback_recipient:clone(buy,K.map((k,i)=>i===pv2i?{...K[ri],isWritable:false,isSigner:false}:i===ri?{...K[pv2i],isWritable:false,isSigner:false}:k)),omit_buyback_pair:clone(buy,K.filter((_,i)=>i!==ri&&i!==ai)),omit_buyback_ata_only:clone(buy,K.filter((_,i)=>i!==ai)),foreign_buyback_recipient:clone(buy,K.map((k,i)=>i===ri?{...k,pubkey:USER}:k)),foreign_buyback_ata:clone(buy,K.map((k,i)=>i===ai?{...k,pubkey:state.userQuoteTokenAccount}:k))};
 const recipients=state.globalConfig?.buybackFeeRecipients??[];for(let j=0;j<recipients.length;j++){const r=recipients[j],ata=getAssociatedTokenAddressSync(state.pool.quoteMint,r,false,state.quoteTokenProgram);cases['authorized_'+j]=clone(buy,K.map((k,i)=>i===ri?{...k,pubkey:r}:i===ai?{...k,pubkey:ata}:k));if(j!==0)cases['mismatch_rec0_ata'+j]=clone(buy,K.map((k,i)=>i===ri?{...k,pubkey:recipients[0]}:i===ai?{...k,pubkey:ata}:k));}
 const watch=[state.userBaseTokenAccount,state.userQuoteTokenAccount,state.pool.poolBaseTokenAccount,state.pool.poolQuoteTokenAccount,K[17].pubkey,K[10].pubkey,buybackAta];const names=['userBase','userQuote','poolBase','poolQuote','coinCreatorFeeAta','protocolFeeAta','buybackAta'];const bh=(await rpc('getLatestBlockhash',[{commitment:'processed'}])).value.blockhash;const cfg={encoding:'base64',sigVerify:false,replaceRecentBlockhash:false,commitment:'processed',accounts:{encoding:'base64',addresses:watch.map(x=>x.toBase58())}};const entries=Object.entries(cases);const payload=entries.map(([name,ix],i)=>({jsonrpc:'2.0',id:i+1,method:'simulateTransaction',params:[raw(ix,bh),cfg]}));let arr;for(let a=0;a<10;a++){const r=await fetch(RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(r.status===429||r.status>=500){await new Promise(x=>setTimeout(x,400+a*300));continue}arr=await r.json();break}if(!Array.isArray(arr))throw Error('no batch '+JSON.stringify(arr));const by=new Map(arr.map(x=>[x.id,x]));const out={};for(let i=0;i<entries.length;i++){const [name]=entries[i],res=by.get(i+1);out[name]=res?.error?{rpcError:res.error}:summarize(res,names);console.log('CASE',name,JSON.stringify(out[name],null,2))}
 console.log('DECISIVE',JSON.stringify({pv2i,ri,ai,correctPv2:correctPv2.toBase58(),foreignPv2:foreignPv2.toBase58(),controlErr:out.control?.err??null,cases:Object.fromEntries(Object.entries(out).map(([n,x])=>[n,{err:x.err??x.rpcError??null,slot:x.slot??null,anchor:x.anchor??[],failed:x.failed??[],returns:x.returns??[]}]))},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
